import boundaries from './region-boundaries.json'

/** Longitude/latitude rings; the first ring of each polygon is its outer edge. */
export type RegionBoundary = readonly (readonly (readonly [number, number])[])[][]

type BoundaryFeature = { id: string; geometry: { coordinates: [number, number][][][] } }

// Generated by scripts/build-region-boundaries.mjs from US Census cartographic boundaries (us-atlas).
const byRegion = new Map<string, RegionBoundary>((boundaries.features as unknown as BoundaryFeature[]).map((feature) => [feature.id, feature.geometry.coordinates]))

export function getRegionBoundary(regionId: string): RegionBoundary | null {
  return byRegion.get(regionId) ?? null
}
